FROM registry.fedoraproject.org/fedora-toolbox:38

LABEL com.github.containers.toolbox="true"

COPY --chmod=755 build.sh /tmp/build.sh

RUN /tmp/build.sh \
    rm -f /tmp/build.sh

RUN ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/yadm
